### ISSUE TITLE
Crash when library in another volume was not found

### ISSUE THREAD

**Issue by FurkanS1821** [akorb/SteamShutdown#26]
I tried to download a game on my USB and created a `SteamLibrary` folder on that volume using Steam. Then I changed my mind and deleted that `SteamLibrary` folder. Now SteamShutdown keeps crashing because it can't find the folder. Recreated the folder and it worked fine. Same happens when I eject the USB.

Logs just in case:
```
6.05.2020 15:08:23: System.TypeInitializationException: 'SteamShutdown.Steam' initializer returned an exception. ---> System.IO.DirectoryNotFoundException: A part of the path 'Z:\SteamLibrary\SteamApps' was not found.
   at: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at: System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at: System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at: System.IO.DirectoryInfo.EnumerateFiles(String searchPattern)
   at: SteamShutdown.Steam.UpdateAppInfos(IEnumerable`1 libraryPaths)
   at: SteamShutdown.Steam..cctor()
   at: SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at: SteamShutdown.CustomApplicationContext..ctor()
   at: SteamShutdown.SteamShutdown.Main()
```

**Comment by akorb** [comment]
Thanks for your report.
This should be already fixed in the newest version. Are you using the latest version? It's only 20 days old.

**Comment by FurkanS1821** [comment]
Yep, forgot to update. While you're here, a "update found" notification wouldn't be bad :P

**Comment by FurkanS1821** [comment]
Weird thing, it still happens with the latest version, with a different log this time
```
7.05.2020 04:49:40: System.TypeInitializationException: 'SteamShutdown.Steam' type initializer returned an exception. ---> System.ArgumentException: Z:\SteamLibrary\SteamApps path is not valid.
   at: System.IO.FileSystemWatcher..ctor(String path, String filter)
   at: SteamShutdown.Steam..cctor()
   at: SteamShutdown.Steam.add_AppInfoChanged(AppInfoChangedEventHandler value)
   at: SteamShutdown.CustomApplicationContext..ctor()
   at: SteamShutdown.SteamShutdown.Main()
```

I gotta note that Z: drive no longer exists. Not just disconnected from the computer, it's in trash bin now.

**Comment by akorb** [comment]
I just updated SteamShutdown.
Could you verifiy if it works now?
https://github.com/akorb/SteamShutdown/releases/tag/v2.3.2

**Comment by FurkanS1821** [comment]
Yep, works now. Thanks for your time.
